//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesProduct
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int SalesPersonID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> UnitsSold { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SalesPerson SalesPerson { get; set; }
    }
}
